site_name: Travel Guide
pages:
    - Home: index.md
    - Travelling Modules: travelmodules.md
    - Commission Specification: comspec.md
    - Experimental Setup: expsetup.md
    - FPGA Configuration: fw.md
    - Software Installation: sw.md
    - Testing Procedure: procedure.md
    - Data Storage: datastorage.md
    - FAQ & Troubleshooting: troubleshooting.md
theme: readthedocs
