site_name: Travel Guide
pages:
    - Home: index.md
    - Travel Pack: travelpack.md
    - Commission Specification: comspec.md
    - Experimental Setup: expsetup.md
    - Programme FPGA: fw.md
    - Software Installation: sw.md
    - Testing Procedure: procedure.md
    - FAQ & Troubleshooting: troubleshooting.md
theme: readthedocs
